audit_header: false
title: Chapel Hill, Durham, & Cary Real Estate Video Blog with Jodi Bakst
description: Our mission at Real Estate Experts is to be your best resource for Chapel Hill, Durham, & Cary real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Real Estate Experts, your professional Chapel Hill, Durham, & Cary Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Jodi Bakst
  title:
  license_number:
  about_markdown: |
    Over the past 20 years, our seasoned team members have worked together to provide outstanding service to our buyers and sellers, while developing a unique partnership to better care for our clients.

    Our team talks and shares ideas with each other regarding our various clients’ needs each day. When you work with any of our realtors, it is just as good as working with the entire team and benefiting from our collective years of experience.
  brand: Real Estate Experts
  brokerage:
  market: Chapel Hill, Durham, & Cary
  address: 501 Eastowne Drive, Ste 140<BR>Chapel Hill, NC 27514
  phone: 919-928-5131
  phone_type:
  phone2:
  phone2_type:
  email: jodi@realestateexperts.net
  url: http://www.realestateexperts.net

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.realestateexperts.net/my-homes-value/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.realestateexperts.net/search-home-sale/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Chapel Hill, Durham, & Cary Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.realestateexperts.net/my-homes-value/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Chapel Hill, Durham, & Cary Home?"
    CTA_text2: "Search the entire MLS for your Chapel Hill, Durham, & Cary home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.realestateexperts.net/search-home-sale/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/teamjodi
  linkedin_url: https://www.linkedin.com/in/jodibakst/
  youtube_url: https://www.youtube.com/user/TeamJodi/
  twitter_url:
  instagram_url: https://instagram.com/ncrealestateexperts
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Chapel Hill, Durham, & Cary Real Estate Podcast with Jodi Bakst'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Chapel Hill, Durham, & Cary Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Real Estate Experts - your professional Chapel Hill, Durham, & Cary Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Chapel Hill, Durham, & Cary, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Jodi Bakst'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Chapel Hill, Durham, & Cary Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#c0393f'
  theme_color: '#727377'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
